CREATE SCHEMA root;
SET SCHEMA root;

CREATE TABLE messages (
  id INT NOT NULL PRIMARY KEY,
  created TIMESTAMP NOT NULL,
  changed TIMESTAMP,
  header VARCHAR(100),
  text CHARACTER LARGE OBJECT,
  picture BINARY LARGE OBJECT,
  visible BOOLEAN DEFAULT TRUE
);

CREATE SEQUENCE messages_id START WITH 1 INCREMENT BY 1;


CREATE TABLE images (
  id INT NOT NULL PRIMARY KEY,
  created TIMESTAMP NOT NULL,
  description VARCHAR(100),
  picture BINARY LARGE OBJECT
);

CREATE SEQUENCE images_id START WITH 1 INCREMENT BY 1;

CREATE TABLE comments (
  id INT NOT NULL PRIMARY KEY,
  id_message INT NOT NULL,
  created TIMESTAMP NOT NULL,
  name VARCHAR(100),
  email VARCHAR(100),
  text CHARACTER LARGE OBJECT,
  id_parent INT
);

CREATE SEQUENCE comments_id START WITH 1 INCREMENT BY 1;
